version: '3'

services:
  ganache-cli:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache:/ganache
      - ./keys:/keys
    command: -n false --wallet.seed 42 --wallet.accountKeysPath /keys/keys.json

  frontend:
    build:
      context: ./lottery-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./lottery-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start

  truffle:
    build:
      context: ./truffle
    volumes:
      - ./truffle:/truffle
      - ./lottery-frontend/src/Lottery.json:/truffle/build/contracts/Lottery.json
      - ./keys:/truffle/keys
    links:
      - ganache-cli
    depends_on:
      - ganache-cli
